```{r 1.1}
rm(list = ls())

# 定义Black-Scholes模型的期权定价公式
analytic_v_put <- function(S, K, r, sigma, T){
  d1 <- (log(S/K) + (r + 0.5 * sigma^2) * T) / (sigma * sqrt(T))
  d2 <- d1 - sigma * sqrt(T)
  put_price <- K * exp(-r * T) * pnorm(-d2) - S * pnorm(-d1)
  return(put_price)
}

phi_X <- function(X,K) pmax(K - X, 0)

# 定义Euler方法
euler_discretization <- function(S0, r, sigma, T,num_steps , N){
  dt <- T / num_steps
  paths <- matrix(0, num_steps+1, N)
  paths[1,] <- S0
  for (i in 1:N){
    for (j in 1:num_steps){
      paths[j+1,i] <- paths[j,i] + r*paths[j,i]*dt + sigma*paths[j,i]*sqrt(dt)*rnorm(1)
    }
  }
  return(paths)
}

# 执行蒙特卡罗模拟
num_steps <- 100 # 模拟时间步数
N <- 1000 # 模拟次数
S0 <- 5
K <- 10
r <- 0.06
sigma <- 0.3
T <- 1

#——————————————————————————————测试部分——————————————————————————————
# 使用解析解公式计算期权价格
analytic_put_price <- analytic_v_put(S0, K, r, sigma, T)

# 使用Euler方法计算期权价格
paths <- euler_discretization(S0, r, sigma, T, num_steps, N)
v_put_price <- mean(phi_X( paths[num_steps+1,],K)) * exp(-r * T)

# 输出结果
# 输出参数设置
cat("Parameter Settings:\n")
cat("S0:", S0, "\n","K:", K, "\n","r:", r, "\n","sigma:", sigma, "\n","T:", T, "\n")
cat("Analytic Vanilla Put Price:", analytic_put_price, "\n")
cat("MC Vanilla Put Price:", v_put_price, "\n")

#——————————————————————————————实验部分——————————————————————————————
# 定义函数来执行实验并计算结果
run_experiment <- function(N, num_repeats) {
  results <- matrix(0, length(N), 2)  # 创建一个空的矩阵来存储结果
  for (i in 1:length(N)) {
    temp_results <- numeric(num_repeats)  # 创建一个临时向量来存储每个N值的重复实验结果
    for (j in 1:num_repeats) {
      paths <- euler_discretization(S0, r, sigma, T, num_steps, N[i])
      temp_results[j] <- mean(phi_X(paths[num_steps+1,], K)) * exp(-r * T)
    }
    results[i,] <- c(mean(temp_results),var(temp_results))  # 计算每个N值的平均结果和方差
  }
  return(results)
}

N_values <- c(30, 50, 100, 200, 500, 1000)
# 运行实验
experiment_results <- run_experiment(N_values, 100)
# 绘制N值与结果的曲线
plot(N_values, experiment_results[,1], type = "l", xlab = "N", ylab = "Result", main = "N vs Result Curve (Mean)")
# 添加水平红虚线
abline(h = analytic_put_price, col = "red", lty = 2)
# 绘制N值与结果的曲线
plot(N_values, experiment_results[,2], type = "l", xlab = "N", ylab = "Result", main = "N vs Result Curve (var)")

```

```{r 1.2}
rm(list = ls())

# 定义Black-Scholes模型的期权定价公式
analytic_b_call <- function(S, K, r, sigma, T){
  d2 <- (log(S/K) + (r -0.5 * sigma^2) * T) / (sigma * sqrt(T))
  res <- exp(-r *T) * pnorm(d2)
  return(res)
}

phi_X <- function(X,K) ifelse(X > K, 1, 0)

# 定义Euler方法
euler_discretization <- function(S0, r, sigma, T,num_steps , N){
  dt <- T / num_steps
  paths <- matrix(0, num_steps+1, N)
  paths[1,] <- S0
  for (i in 1:N){
    for (j in 1:num_steps){
      paths[j+1,i] <- paths[j,i] + r*paths[j,i]*dt + sigma*paths[j,i]*sqrt(dt)*rnorm(1)
    }
  }
  return(paths)
}

num_steps <- 100 # 模拟时间步数
N <- 1000 # 模拟次数
S0 <- 0.5
K <- 0.5
r <- 0.1
sigma <- 0.5
T <- 0.5

#——————————————————————————————测试部分——————————————————————————————
# 使用解析解公式计算期权价格
analytic_call <- analytic_b_call(S0, K, r, sigma, T)

# 使用Euler方法计算期权价格
paths <- euler_discretization(S0, r, sigma, T, num_steps, N)
MC_b_call <- mean(phi_X(paths[num_steps+1,],K))* exp(-r * T)

# 输出结果
# 输出参数设置
cat("Parameter Settings:\n")
cat("S0:", S0, "\n","K:", K, "\n","r:", r, "\n","sigma:", sigma, "\n","T:", T, "\n")
cat("Analytic Binary Call Price:", analytic_call, "\n")
cat("MC Binary call Price:", MC_b_call, "\n")

#——————————————————————————————实验部分——————————————————————————————
# 定义函数来执行实验并计算结果
run_experiment <- function(N, num_repeats) {
  results <- matrix(0, length(N), 2)  # 创建一个空的矩阵来存储结果
  for (i in 1:length(N)) {
    temp_results <- numeric(num_repeats)  # 创建一个临时向量来存储每个N值的重复实验结果
    for (j in 1:num_repeats) {
      paths <- euler_discretization(S0, r, sigma, T, num_steps, N[i])
      temp_results[j] <-  mean(phi_X(paths[num_steps+1,],K))* exp(-r * T)
    }
    results[i,] <- c(mean(temp_results),var(temp_results))  # 计算每个N值的平均结果和方差
  }
  return(results)
}

N_values <- c(30, 50)
# 运行实验
experiment_results <- run_experiment(N_values, 10)
# 绘制N值与结果的曲线
plot(N_values, experiment_results[,1], type = "l", ylab = "Result", main = "N vs Result Curve (Mean)")
# 添加水平红虚线
abline(h = analytic_call, col = "red", lty = 2)
# 绘制N值与结果的曲线
plot(N_values, experiment_results[,2], type = "l", ylab = "Result", main = "N vs Result Curve (var)")
```
```{r 1.3}
rm(list = ls())

analytic_uob_call <- function(S,K,H, r, sigma, T) {
  lambda <- (r+sigma^2/2)/sigma^2
  y1 <- log(H^2/(S*K))/(sigma*sqrt(T))+lambda*sigma*sqrt(T)
  y2 <- log(H/S)/ (sigma * sqrt(T)) +lambda*sigma*sqrt(T) 
  x1 <- log(S/K)/ (sigma * sqrt(T)) +lambda*sigma*sqrt(T)
  x2 <- log(S/H)/ (sigma * sqrt(T)) +lambda*sigma*sqrt(T)
  A <- S*pnorm(x1)-K*exp(-r*T)*pnorm(x1-sigma*sqrt(T))
  B <- S*pnorm(x2)-K*exp(-r*T)*pnorm(x2-sigma*sqrt(T))
  C <- S*(H/S)^(2*lambda)*pnorm(-y1)-K*exp(-r*T)*(H/S)^(2*lambda-2)*pnorm(-y1+sigma*sqrt(T))
  D <- S*(H/S)^(2*lambda)*pnorm(-y2)-K*exp(-r*T)*(H/S)^(2*lambda-2)*pnorm(-y2+sigma*sqrt(T))
  cuo <-  A-B+C-D
          
  
  if(K>H){
    return (0)
  } else if (K<=H) {
    return (cuo)
  }
}

phi_X <- function(X,K,B){
  barrier_hit <- apply(X, 2, function(x) max(x) >= B)  # 检查每次模拟是否达到barrier
  payoff <- pmax(X[nrow(X), ] - K, 0)  # 计算期权到期时的支付
  payoff[barrier_hit] <- 0  # 如果价格超过barrier，期权价值为0
  return (payoff)
}

# 定义Euler方法
euler_discretization <- function(S0, r, sigma, T,num_steps , N){
  dt <- T / num_steps
  paths <- matrix(0, num_steps+1, N)
  paths[1,] <- S0
  for (i in 1:N){
    for (j in 1:num_steps){
      paths[j+1,i] <- paths[j,i] + r*paths[j,i]*dt + sigma*paths[j,i]*sqrt(dt)*rnorm(1)
    }
  }
  return(paths)
}

num_steps <- 100 # 模拟时间步数
N <- 1000 # 模拟次数
S0 <- 5
K <- 6
r <- 0.05
sigma <- 0.3
T <- 1
B <- 8

#——————————————————————————————测试部分——————————————————————————————
# 使用解析解公式计算期权价格
analytic_call <- analytic_uob_call(S0, K, B, r, sigma, T)

# 使用Euler方法计算期权价格
paths <- euler_discretization(S0, r, sigma, T, num_steps, N)
MC_uob_call <- mean(phi_X(paths,K,B)) * exp(-r * T)

# 输出结果
# 输出参数设置
cat("Parameter Settings:\n")
cat("S0:", S0, "\n","K:", K, "\n","r:", r, "\n","sigma:", sigma, "\n","T:", T, "\n")
cat("Analytic Up-and-Out Barrier Put Price:", analytic_call, "\n")
cat("MC Up-and-Out Barrier Price:", MC_uob_call, "\n")

#——————————————————————————————实验部分——————————————————————————————
# 定义函数来执行实验并计算结果
run_experiment <- function(N, num_repeats) {
  results <- matrix(0, length(N), 2)  # 创建一个空的矩阵来存储结果
  for (i in 1:length(N)) {
    temp_results <- numeric(num_repeats)  # 创建一个临时向量来存储每个N值的重复实验结果
    for (j in 1:num_repeats) {
      paths <- euler_discretization(S0, r, sigma, T, num_steps, N[i])
      temp_results[j] <- mean(phi_X(paths,K,B)) * exp(-r * T)
    }
    results[i,] <- c(mean(temp_results))  # 计算每个N值的平均结果和方差
  }
  return(results)
}

N_values <- c(30, 50, 100, 200, 500, 1000)
# 运行实验
experiment_results <- run_experiment(N_values, 100)
# 绘制N值与结果的曲线
plot(N_values, experiment_results[,1], type = "l", xlab = "", ylab = "Result",
                                            ylim = range(c(experiment_results[,1], analytic_call)),
                                            main = "N vs Result Curve (Mean)")
# 添加水平红虚线
abline(h = analytic_call, col = "red", lty = 2)
# 绘制N值与结果的曲线
plot(N_values, experiment_results[,2], type = "l", xlab = "", ylab = "Result", main = "N vs Result Curve (var)")
```
```{r 2}
rm(list = ls())

phi_X <- function(X,K) pmax( colMeans(X)- K, 0)

# 定义Euler方法
euler_discretization <- function(S0, r, sigma, T,num_steps , N ){
  dt <- T / num_steps
  # 申明变量
  paths <- matrix(0, num_steps+1, N)
  paths[1,] <- S0
  antithetic_paths <- matrix(0, num_steps+1, N)
  antithetic_paths[1,] <- S0
  # 采样标准正态
  Z <- matrix(rnorm(num_steps*N), nrow=num_steps)
  for (i in 1:N){
    for (j in 1:num_steps){
      paths[j+1,i] <- paths[j,i]* (1 + r*dt + sigma*sqrt(dt)*Z[j,i] ) 
      antithetic_paths[j+1,i] <- antithetic_paths[j,i]* (1 + r*dt - sigma*sqrt(dt)*Z[j,i] )
    }
  }
  return(list(paths, antithetic_paths))
}

# 建模参数
S0 <- 100
K <- 90
r <- 0.05
sigma <- 0.3
T <- 2
m <- 20
N <- 50

# 使用Euler方法计算期权价格
result <- euler_discretization(S0, r, sigma, T, num_steps=m, N)
paths <- result[[1]]
anti_paths <- result[[2]]
hST_samples <- phi_X(paths[-1,],K)
# 对立变量方法
hST_AV_samples <- (hST_samples+phi_X(anti_paths[-1,],K))/2
# 控制变量方法, 直接用轨迹最后时刻作为随机变量Xi
c <- - cov(paths[(m+1),],hST_samples)/var(paths[(m+1),])
Eh0 <- S0*(1+r*T/m)^m
hST_CV_samples <- hST_samples + c*(paths[(m+1),]- Eh0)

cat("h(ST) samples     mean: ",mean(hST_samples),"var: " ,var(hST_samples) ,"\n")
cat("h(ST)_AV samples  mean: ",mean(hST_AV_samples),"var: " ,var(hST_AV_samples) ,"\n")
cat("h(ST)_CV samples  mean: ",mean(hST_CV_samples),"var: " ,var(hST_CV_samples) ,"\n")

cat("h(S0) est: ",mean(hST_samples)* exp(-r * T),"\n")
cat("h(S0)_AV est: ",mean(hST_AV_samples)* exp(-r * T),"\n")
cat("h(S0)_CV est: ",mean(hST_CV_samples)* exp(-r * T),"\n")

```
